resource "local_file" "inventory" {
  content         = <<-EOF
# Ansible inventory containing variable values from Terraform.
# Generated by Terraform.
---
all:
  children:
    proxy:
      hosts:
        ${yandex_compute_instance.proxy.hostname}.${var.domain}:
          ansible_host: ${yandex_compute_instance.proxy.network_interface.0.nat_ip_address}
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
          letsencrypt_staging: ${local.workspace["letsencrypt_staging"]}
    db:
      hosts:
        ${yandex_compute_instance.mysql[0].hostname}.${var.domain}:
          ansible_host: ${yandex_compute_instance.mysql[0].network_interface.0.ip_address}
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -J ubuntu@${yandex_compute_instance.proxy.network_interface[0].nat_ip_address}"
          mysql_replication_role: 'master'
        ${yandex_compute_instance.mysql[1].hostname}.${var.domain}:
          ansible_host: ${yandex_compute_instance.mysql[1].network_interface.0.ip_address}
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -J ubuntu@${yandex_compute_instance.proxy.network_interface[0].nat_ip_address}"
          mysql_replication_role: 'slave'

    app:
      hosts:
        ${yandex_compute_instance.app.hostname}.${var.domain}:
          ansible_host: ${yandex_compute_instance.app.network_interface.0.ip_address}
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -J ubuntu@${yandex_compute_instance.proxy.network_interface[0].nat_ip_address}"

    git:
      hosts:
        ${yandex_compute_instance.gitlab.hostname}.${var.domain}:
          ansible_host: ${yandex_compute_instance.gitlab.network_interface.0.ip_address}
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -J ubuntu@${yandex_compute_instance.proxy.network_interface[0].nat_ip_address}"

    monitoring:
      hosts:
        ${yandex_compute_instance.monitoring.hostname}.${var.domain}:
          ansible_host: ${yandex_compute_instance.monitoring.network_interface.0.ip_address}
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -J ubuntu@${yandex_compute_instance.proxy.network_interface[0].nat_ip_address}"
  vars:
    virtual_domain: ${var.domain}
    ansible_user: ubuntu
    ansible_connection: ssh

    EOF
  filename        = "../ansible/inventory.yml"
  file_permission = "0644"

  depends_on = [
    yandex_compute_instance.proxy,
    yandex_compute_instance.mysql,
    yandex_compute_instance.app,
    yandex_compute_instance.gitlab,
    yandex_compute_instance.monitoring
  ]
}
