Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.box_check_update = false
  config.vm.define "devnet01"
  config.vm.hostname = "devnet01"
  config.vm.network "public_network", ip: "192.168.10.71"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "devnet01"
    vb.gui = false
    vb.memory = "2048"
	vb.cpus = 2
	vb.check_guest_additions = false
  end
  config.vm.provision "shell", inline: <<-SHELL
    echo === APT UPDATE  ===
    apt-get update
    echo === APT INSTALL ===
    apt-get install -y mc
  SHELL
  config.vm.post_up_message = "=== ALL DONE. U CAN START LEARNING"
end