---
# General config.
gitlab_domain: gitlab.{{ virtual_domain }}
gitlab_external_url: "http://{{ gitlab_domain }}/"
gitlab_git_data_dir: "/var/opt/gitlab/git-data"
gitlab_edition: "gitlab-ce"
gitlab_version: ''
gitlab_backup_path: "/var/opt/gitlab/backups"
gitlab_config_template: "gitlab.rb.j2"
gitlab_package_version_separator: '='
gitlab_repository_installation_script_url: "https://packages.gitlab.com/install/repositories/gitlab/{{ gitlab_edition }}/script.deb.sh"
gitlab_modules: [ 'curl', 'tzdata', 'perl', 'gnupg2' ]

# SSL Configuration.
gitlab_redirect_http_to_https: false
# SSL Self-signed Certificate Configuration.
gitlab_create_self_signed_cert: false
# LetsEncrypt configuration.
gitlab_letsencrypt_enable: false
# LDAP Configuration.
gitlab_ldap_enabled: false
# SMTP Configuration
gitlab_smtp_enable: false

# Dependencies.
gitlab_dependencies:
  - openssh-server
  - postfix
  - curl
  - openssl
  - tzdata